default: styles/custom.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
fairy-floss: styles/fairy-floss.scss
macaron: styles/macaron.scss
fixmacaron: styles/macaron (fix).scss
